const departments=[{name:"BCA",icon:"💻",description:"Bachelor of Computer Applications — programming, databases, web development and computing.",rooms:"204, 205, 206"},{name:"BBA",icon:"💼",description:"Bachelor of Business Administration — management, marketing, finance and entrepreneurship.",rooms:"201, 202, 203"},{name:"B.Com",icon:"📊",description:"Bachelor of Commerce — accounting, finance, taxation and business studies.",rooms:"304, 305, 306"},{name:"Kannada",icon:"🪔",description:"Kannada Department and Kuvempu Kannada Sangha activities.",rooms:"401, 402"},{name:"English",icon:"📖",description:"English language, literature and communication.",rooms:"403, 404"}];
const timetable=[{time:"09:00 AM",subject:"Database Management",department:"BCA",room:"204"},{time:"10:00 AM",subject:"Web Development",department:"BCA",room:"205"},{time:"11:00 AM",subject:"Principles of Management",department:"BBA",room:"201"},{time:"12:00 PM",subject:"Financial Accounting",department:"B.Com",room:"304"},{time:"02:00 PM",subject:"English Literature",department:"English",room:"403"}];
const events=[{name:"Inter-Collegiate Hackathon 2026",date:"Coming Soon",venue:"C.B. Bhandari Jain College",icon:"💻"},{name:"AI Debate Competition",date:"28th",venue:"College Campus",icon:"🎤"},{name:"Folk Song & Dance Competition",date:"30/09/2026",venue:"College Auditorium",icon:"🎭"},{name:"Digital Cell Workshop",date:"Coming Soon",venue:"College Campus",icon:"🚀"}];
const faculty=[{name:"BCA Faculty",department:"BCA",subject:"Computer Applications",icon:"👨‍💻"},{name:"BBA Faculty",department:"BBA",subject:"Management & Business",icon:"👩‍💼"},{name:"B.Com Faculty",department:"B.Com",subject:"Commerce & Accounting",icon:"👨‍🏫"},{name:"Kannada Faculty",department:"Kannada",subject:"Kannada Language & Literature",icon:"📚"},{name:"English Faculty",department:"English",subject:"English Language & Literature",icon:"📖"}];
const rooms=[{room:"201–203",location:"Block A",floor:"2nd Floor",status:"BBA Classrooms"},{room:"204–206",location:"Block A",floor:"2nd Floor",status:"BCA Classrooms"},{room:"304–306",location:"Block B",floor:"3rd Floor",status:"B.Com Classrooms"},{room:"401–402",location:"Block B",floor:"4th Floor",status:"Kannada Department"},{room:"403–404",location:"Block B",floor:"4th Floor",status:"English Department"},{room:"Auditorium",location:"Main Campus",floor:"Events Zone",status:"College Events"}];
const notices=[{title:"Hackathon Registration",text:"Registration information for the Inter-Collegiate Hackathon will appear here.",icon:"💻"},{title:"Digital Cell",text:"Watch this space for upcoming Digital Cell activities and competitions.",icon:"📱"},{title:"Campus Events",text:"Check the Events section for competitions, workshops and student activities.",icon:"◈"}];
function showPage(id){document.querySelectorAll(".page").forEach(function(p){p.classList.remove("active-page")});document.getElementById(id).classList.add("active-page");document.querySelectorAll(".nav").forEach(function(b){b.classList.remove("active")});document.querySelectorAll(".nav").forEach(function(b){if((b.getAttribute("onclick")||"").includes("'"+id+"'"))b.classList.add("active")});window.scrollTo({top:0,behavior:"smooth"})}
function loadDashboard(){document.getElementById("todayClasses").innerHTML=timetable.slice(0,3).map(function(x){return '<div class="class-item"><div><b>'+x.subject+'</b><small>'+x.department+' · Room '+x.room+'</small></div><b>'+x.time+'</b></div>'}).join("");document.getElementById("dashboardEvents").innerHTML=events.slice(0,3).map(function(x){return '<div class="class-item"><div><b>'+x.icon+' '+x.name+'</b><small>'+x.venue+'</small></div><b>'+x.date+'</b></div>'}).join("");document.getElementById("roomCount").textContent=rooms.length;document.getElementById("eventCount").textContent=events.length;document.getElementById("facultyCount").textContent=faculty.length;document.getElementById("noticeCount").textContent=notices.length}
function loadTimetable(){document.getElementById("timetableData").innerHTML=timetable.map(function(x){return '<tr><td><b>'+x.time+'</b></td><td>'+x.subject+'</td><td>'+x.department+'</td><td>'+x.room+'</td></tr>'}).join("")}
function loadEvents(){document.getElementById("eventCards").innerHTML=events.map(function(x){return '<div class="card"><div class="card-icon">'+x.icon+'</div><h3>'+x.name+'</h3><p>📅 '+x.date+'<br>⌖ '+x.venue+'</p><span class="badge">Upcoming</span></div>'}).join("")}
function loadDirectory(type,button){document.querySelectorAll(".tab").forEach(function(x){x.classList.remove("active")});if(button)button.classList.add("active");var data=type==="faculty"?faculty:type==="rooms"?rooms:departments;document.getElementById("directoryCards").innerHTML=data.map(function(x){if(type==="faculty")return '<div class="card"><div class="card-icon">'+x.icon+'</div><h3>'+x.name+'</h3><p>Department: '+x.department+'<br><br>Area: '+x.subject+'</p></div>';if(type==="rooms")return '<div class="card"><div class="card-icon">⌖</div><h3>Room '+x.room+'</h3><p>Location: '+x.location+'<br>Floor: '+x.floor+'<br>Purpose: '+x.status+'</p><span class="badge">Campus location</span></div>';return '<div class="card"><div class="card-icon">'+x.icon+'</div><h3>'+x.name+'</h3><p>'+x.description+'</p><span class="badge">Rooms: '+x.rooms+'</span></div>'}).join("")}
function loadNotices(){document.getElementById("noticeCards").innerHTML=notices.map(function(x){return '<div class="card"><div class="card-icon">'+x.icon+'</div><h3>'+x.title+'</h3><p>'+x.text+'</p><span class="badge">Active notice</span></div>'}).join("")}
function showLocation(name){var info={"Main Gate":"Primary campus entrance and visitor access point.","Block A":"Academic block containing BCA and BBA classrooms.","Block B":"Academic block containing B.Com and Arts departments.","Auditorium":"Main venue for college events, competitions and talks.","Library":"Study and reference zone — replace this description with your actual library location."};document.getElementById("locationInfo").innerHTML="<b>"+name+"</b><p>"+(info[name]||"Campus location")+"</p>";toast("Selected "+name)}
function addMessage(text,type){var box=document.getElementById("chatMessages"),el=document.createElement("div");el.className="message "+type;el.innerHTML=text;box.appendChild(el);box.scrollTop=box.scrollHeight}
function askQuestion(q){document.getElementById("question").value=q;sendQuestion()}
function handleEnter(e){if(e.key==="Enter")sendQuestion()}
function sendQuestion(){var input=document.getElementById("question"),q=input.value.trim();if(!q)return;addMessage(q,"user");input.value="";setTimeout(function(){addMessage(generateAnswer(q),"ai")},250)}
function generateAnswer(question){var q=question.toLowerCase();if(q.includes("306")||q.includes("304"))return "📊 <b>Commerce Block</b><br><br>Rooms 304–306 are listed for B.Com classes on the 3rd Floor of Block B.";if(q.includes("bca"))return "💻 <b>BCA Department</b><br><br>BCA is listed in Block A, with sample rooms 204–206. Ask me for a specific room or class.";if(q.includes("bba"))return "💼 <b>BBA Department</b><br><br>BBA is listed in Block A, with sample rooms 201–203.";if(q.includes("class")||q.includes("timetable")||q.includes("today"))return "▣ <b>Today's sample schedule</b><br><br>09:00 — Database Management — Room 204<br>10:00 — Web Development — Room 205<br>11:00 — Principles of Management — Room 201";if(q.includes("event")||q.includes("competition")||q.includes("hackathon"))return "◈ <b>Upcoming events</b><br><br>💻 Inter-Collegiate Hackathon 2026<br>🎤 AI Debate Competition<br>🎭 Folk Song & Dance Competition<br>🚀 Digital Cell Workshop";if(q.includes("faculty")||q.includes("teacher")||q.includes("professor"))return "◎ <b>Faculty directory</b><br><br>BCA · BBA · B.Com · Kannada · English faculty are available in the Directory.";if(q.includes("room"))return "⌖ I can search the campus room directory. Try a room number such as <b>204</b>, <b>306</b>, or <b>Auditorium</b>.";if(q.includes("hello")||q.includes("hi")||q.includes("hey"))return "✦ Hello! I'm CampusPulse AI. Ask me about rooms, classes, faculty, departments or events.";return "🤔 I don't have that campus detail yet.<br><br>Try asking about <b>rooms, BCA, BBA, B.Com, classes, faculty or events</b>."}
function globalSearch(value){var box=document.getElementById("searchResults"),q=value.trim().toLowerCase();if(!q){box.classList.add("hidden");box.innerHTML="";return}var results=[];rooms.forEach(function(x){if((x.room+" "+x.location+" "+x.status).toLowerCase().includes(q))results.push(["Room","Room "+x.room,x.location+" · "+x.status])});faculty.forEach(function(x){if((x.name+" "+x.department+" "+x.subject).toLowerCase().includes(q))results.push(["Faculty",x.name,x.department])});events.forEach(function(x){if((x.name+" "+x.venue).toLowerCase().includes(q))results.push(["Event",x.name,x.venue])});departments.forEach(function(x){if((x.name+" "+x.description).toLowerCase().includes(q))results.push(["Department",x.name,x.description])});box.innerHTML=results.length?results.slice(0,7).map(function(r){return '<div class="search-result"><b>'+r[0]+' · '+r[1]+'</b><small>'+r[2]+'</small></div>'}).join(""):"<div class='search-result'><b>No matching campus record</b><small>Try a room number, department or event name.</small></div>";box.classList.remove("hidden")}
function toggleTheme(){toast("Theme controls will expand in the next version")}
function toast(text){var t=document.getElementById("toast");t.textContent=text;t.classList.add("show");setTimeout(function(){t.classList.remove("show")},1800)}
loadDashboard();loadTimetable();loadEvents();loadDirectory("faculty",document.querySelector(".tab"));loadNotices();